### ISSUE TITLE
Cookie clearing exceptions don't work after Arkenfox 102

### ISSUE THREAD

**Issue by flexagoon** [arkenfox/user.js#1495]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 102 on NixOS Unstable
  - Steps to Reproduce (STR):
  	- Go to GitHub
  	- Allow it to save cookies via the Ctrl+I menu
  	- Log in
  	- Restart Firefox
  - Expected result:
  	You are still logged in
  - Actual result:
  	You are no longer logged in
  - Console errors and warnings: none
  - Anything else you deem worth mentioning:

<details>
<summary>My overrides</summary>

```js
// CONVINIENCE
// -----------------------------------------------
// Enable urlbar searching
user_pref("keyword.enabled", true); 
user_pref("browser.search.suggest.enabled", true);
user_pref("browser.urlbar.suggest.searches", true);
// Enable session restore
user_pref("browser.startup.page", 3);
// Remember the file download location
user_pref("browser.download.useDownloadDir", true);
// Don't clear history
user_pref("privacy.clearOnShutdown.history", false);
user_pref("privacy.cpd.history", false);
// Enable DRM
user_pref("media.eme.enabled", true);

// REMOVE USELESS FEATURES
// -----------------------------------------------
// Disable search engine suggestions in the urlbar
user_pref("browser.urlbar.suggest.engines", false);
// Disable container tabs
user_pref("privacy.userContext.enabled", false);
user_pref("privacy.userContext.ui.enabled", false);
// Don't save passwords
user_pref("signon.rememberSignons", false);
```

</details>

---

This worked as intended until the last version, but since v102 it no longer works.

**Comment by Thorin-Oakenpants** [comment]
Worksforme (windows). I did have three instances where it did clear exceptions, but it seems stable now - it may be a case of not cleaning closing the app - I do use the quit button, but I did read a recent ticket about longer/munged shutdowns - IDK if that applies. Note: this non-clean shutdown sanitize issue is [fixed in FF103](https://bugzilla.mozilla.org/show_bug.cgi?id=1771024)

^ IDK if that is what is causing your issue. What app are you using - snap? flat? etc? How are you closing Firefox?

Otherwise, the only thing that sticks out is not clearing history, but that _shouldn't_ affect it. I have not tested.

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/firefox/comments/vrswmo/firefox_v102_occasionally_losing_session_data_on/

**Comment by Thorin-Oakenpants** [comment]
next time it happens, check `privacy.sanitize.didShutdownSanitize`

**Comment by Thorin-Oakenpants** [comment]
@CptDinosaur `firefox is still running - quit cancel` - that sounds like the issue about not exiting gracefully, fixed in FF103 (when you don't get a clean shutdown `privacy.sanitize.didShutdownSanitize` would exist as `true`, then it does a sanitize on startup but doesn't respect exceptions)

I suspect OP is the same

**Comment by CptDinosaur** [comment]
Restarted with a clean shutdown and I still dont have `privacy.sanitize.didShutdownSanitize`

I'll try forcing a non-graceful shutdown and see if that's the cause

**Comment by Thorin-Oakenpants** [comment]
> While waiting for v103, is there anything I can do in the meantime so I don't keep losing all my cookies?

Well, if it's not an ungraceful exit in some of these cases, then 103 won't fully solve it (unless it was something else that 103 fixes). In the meantime, you can't use the lifetimePolicy pref (it will just reset and migrate you), and you can't disable onShutdown and use Ctrl-Shift-Del manually when you go to bed, because that doesn't respect exceptions

Has anyone filled a bugzilla on this.

**Comment by Thorin-Oakenpants** [comment]
> Restarted with a clean shutdown and I still dont have privacy.sanitize.didShutdownSanitize

Maybe also set `browser.sanitizer.loglevel` = `All`. Then check the browser console (ctrl-Shift-J) on startup

**Comment by aleyvo** [comment]
I was using FF 102 and lost my exceptions data twice because of power loss and once because of this intermittent wiping of data on graceful exits.
If you're like me and have significant amounts of website exceptions, that's my advice: revert back to [FF 101](https://ftp.mozilla.org/pub/firefox/releases/101.0.1/).
Since I did this, no issues so far. I'm waiting for FF 103 to be released.

PS: I thought "101" was meant to learn the basics, not to spoil the basics (in 102.)

**Comment by CptDinosaur** [comment]
> I was using FF 102 and lost my exceptions data twice because of power loss and once because of this intermittent wiping of data on graceful exits. If you're like me and have significant amounts of website exceptions, that's my advice: revert back to [FF 101](https://ftp.mozilla.org/pub/firefox/releases/101.0.1/). Since I did this, no issues so far. I'm waiting for FF 103 to be released.
> 
> PS: I thought "101" was meant to learn the basics, not to spoil the basics (in 102.)

Can't downgrade, it won't let you use the new profile since it's been upgraded to be incompatible

**Comment by aleyvo** [comment]
I'll create a test profile with a separate FF 102 installation and try to reproduce this intermittent wiping of data on graceful exits.

> do you simply close the app from the UI and that happens at times?

When it occurred to me, I quit using Ctrl+Shift+Q

> are ALL cookies cleared or only some of them?

All of them.

> exceptions still exist but they are ignored, correct?

Exactly

**Comment by CptDinosaur** [comment]
> power losses, people shutting down their machine with firefox open etc. all fall under the "ungraceful exit" umbrella which is a known issue that will be fixed (it already is in Nightly for example). we are more interested in exceptions being ignored on graceful/normal closes right? I don't think we have found a way to reliable reproduce this. that would be important, me and pants cannot reproduce this so far.
> 
> I think it would be useful if you people stick to FF102, create a new profile and apply the latest user.js to it; for example, knowing it only occurs in profiles where lifetime was set to 2 at some point would already be valuable IMO. of course feel free to say no if it sounds annoying. some questions on graceful exits:
> 
>     * do you simply close the app from the UI and that happens at times?
> 
>     * are ALL cookies cleared or only some of them?
> 
>     * exceptions still exist but they are ignored, correct?

I think for me it's been when I get the "Firefox is still running" error.
Not sure if it's happened with fully graceful exits, don't think so? But it might have. It's happened numerous times now

**Comment by aleyvo** [comment]
>Maybe also set browser.sanitizer.loglevel = All. Then check the browser console (ctrl-Shift-J) on startup

This seems promising.

**Comment by aleyvo** [comment]
>Can't downgrade, it won't let you use the new profile since it's been upgraded to be incompatible

That's the downside. I had to uninstall everything, install FF 101, create a new profile with arkenfox 101, import my bookmarks, and install uBO again :/

**Comment by fxbrit** [comment]
@CptDinosaur  in the case of ungraceful exits it's a known issue that's fixed in 103+. if it's too annoying you could take a chance and install Beta or Nightly in the meantime I guess? not saying you absolutely should, but it works side by side with Stable, so maybe it's worth it for you.

***

@aleyvo thanks, I'm trying the same on macOS, no luck so far. are you on windows?


I'll stop the noise for now, if you guys open a bugzilla (you should since you had the issue at least once) please link it so I can hopefully add to it at some point.

**Comment by aleyvo** [comment]
Yes, I'm on Windows.

I'll try with a portable FF or with Sandbox. If I manage to reproduce it, I'll open a bugzilla and link it here for you guys.

**Comment by flexagoon** [comment]
I don't know how to reproduce it either, I just tried and it did not log me out this time. It just does it randomly sometimes.

Or maybe the times when it logged me out were actually me rebooting my computer with firefox open? I'll tell you when the issue happens next time.

**Comment by flexagoon** [comment]
By the way, yes, ungracefully exiting firefox does log me out of all websites. So it is possible that the problem was with that in my case.

However, people are reporting that they also have this even if they close firefox properly, so I'll keep this issue open for now.

**Comment by aleyvo** [comment]
Been using FF 102 with AF 102 through the day. Tried closing it in multiple combined ways: using Ctrl+Shift+Q; using "X"; using the UI's "Exit"; while loading lots of tabs simultaneously; with multiple tabs opened in multiple windows; with PB window active; while FF was hanging/unresponsive; enabling/disabling the Session Restore recipe; triggering the migration code (lifetimePolicy) a couple times; letting the Browser Console open (orphan); letting the Library window open (orphan); while playing audio/videos; while downloading files; with Bookmarks shown/not shown...

Nothing so far, didn't manage to reproduce the issue again.

**Comment by Thorin-Oakenpants** [comment]
sounds like a race condition

**Comment by Thorin-Oakenpants** [comment]
You can also flip both `devtools.console.stdout.chrome` and `devtools.console.stdout.content` to true

**Comment by gmvk** [comment]
This may depend on the file system. I have all my cookies disappear on btrfs.

**Comment by gmvk** [comment]
Also stopped clearing gmp-clearkey cookies, dropbox sets them.

**Comment by flexagoon** [comment]
Ok, looks like in my case, the issue actually happens only when my laptop battery dies while Firefox is open, so it is related to 'ungraceful exit'.

**Comment by Thorin-Oakenpants** [comment]
There's still something fucking wonky going on. I've lost mine 5 times, and it's not from improper shutdowns

**Comment by fxbrit** [comment]
[changelog for 102.0.1](https://www.mozilla.org/en-US/firefox/102.0.1/releasenotes/) says:

> Fixed Delete cookies and site data when Firefox is closed checkbox getting disabled on startup

https://bugzilla.mozilla.org/show_bug.cgi?id=1777419

**Comment by cronyakatsuki** [comment]
I lost my logins about 13 times today, Google gonna send swat team soon if this aint fixed.

**Comment by Thorin-Oakenpants** [comment]
> Google gonna send swat team soon if this aint fixed

party van 🎉 

> changelog for 102.0.1 says:

They backed out the migration code. This has no bearing on AF settings, as I would have been moving to resetting lifetimePolicy pref and using onShutdown anyway, as was planned to do so at least one release before migration. The cosmetic UI issue is immaterial.

But, and I have not tested - this probably means you can override back to the old settings (i.e onShutdown cookies and offlineApps = false, lifetimePolicy = 2) and this _should_ work to stop bulk sanitizing issues.

What annoys me is that ESR102 users from here on in are a bit messed up. Would be nice if they backported the 103 fix for ungraceful onShutdown's to respect exceptions onStartup - at a minimum.

**Comment by atomGit** [comment]
pants, just so you know, `privacy.sanitize.didShutdownSanitize` apparently doesn't exist on FF for Linux

**Comment by Thorin-Oakenpants** [comment]
well, it actually doesn't exist on any platform - it was deprecated in [FF58](https://bugzilla.mozilla.org/show_bug.cgi?id=1434414)

**Comment by romelsalwi** [comment]
I have faced this issue since the 102 update. It didn't occur in previous version. Is there a way to addin exception to override.js?

**Comment by Thorin-Oakenpants** [comment]
The reason it didn't occur until 102 for AF users, is that we used the lifetimePolicy pref instead of clearing all cookies + offlineApps data on close. 102 then had a migration to reset lifetimePolicy etc, effectively making it useless, and we had to change. They have now backed that out in FF/ESR102.1.

There are two issues going on here. One is the sanitize onStartup fallback (when sanitize onShutdown fails) doesn't respect exceptions, this is fixed in 103. This means when Firefox doesn't exit gracefully, e.g. exiting the app with the OS shutdown, or crashing, then everything gets wiped.

The second issue is this is still happening for users who do (presumably) exit gracefully - i.e not crashing, and are exiting nicely with processes etc. Something is either failing to respect exceptions onShutdown, or it is triggering a sanitize on startup.

In 103, we HAVE to move to using onShutdown (and ignoring lifetimePolicy) because that migration code is there in 103+, and all we would be doing is triggering the migration code every time we start the browser. I DO NOT KNOW if the issue will persist in 103 - it depends on the cause: some permission thing, some race condition, something else, IDFK.

But for 102, and since this is also used for ESR users, I am putting out a dot release to revert the behavior.

**Comment by Thorin-Oakenpants** [comment]
This is #1507 - basically changes are
- `network.cookie.lifetimePolicy` = `2`
- `privacy.clearOnShutdown.cookies` + `privacy.clearOnShutdown.offlineApps` = false

**Comment by Thorin-Oakenpants** [comment]
[AF 102-1 is out](https://github.com/arkenfox/user.js/releases/tag/102.1) which importantly provides stability for ESR102 users

Closing. If exceptions are not honored in 103+ (and we HAVE TO revert back to using onShutdown prefs in 103+), then we can open a new issue and take it from there

**Comment by gmvk** [comment]
test
